GestionMusiques/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^musiques/', include('musiques.urls')),
]

musiques/urls.py
from django.conf.urls import url
from .views import *

app_name = 'musiques'
urlpatterns = [
    # Urls des musiques
    url(r'^create/$',
        MorceauCreateView.as_view(), name='morceau-create'),
    url(r'^(?P<pk>\d+)$',
        MorceauDetailView.as_view(), name='morceau-detail'),
    url(r'^liste/$',
        MorceauListView.as_view(), name='morceau-liste'),
    url(r'^update/(?P<pk>\d+)$',
        MorceauUpdateView.as_view(), name='morceau-update'),
    url(r'^delete/(?P<id>\d+)$', deleteMorceau, name='morceau-delete'),
    # Urls de l'artiste
    url(r'^artiste/create/$',
        ArtisteCreateView.as_view(), name='artiste-create'),
    url(r'^artiste/(?P<pk>\d+)',
        ArtisteDetailView.as_view(), name='artiste-detail'),
    url(r'^artiste/update/(?P<pk>\d+)',
        ArtisteUpdateView.as_view(), name='artiste-update'),
    url(r'^artiste/liste/$',
        ArtisteListView.as_view(), name='artiste-liste'),
    url(r'^artiste/delete/(?P<id>\d+)$', deleteArtiste, name='artiste-delete')
]

musiques/models.py
from musiques.artistes.model import Artiste
from musiques.morceau.model import Morceau

musiques/artistes/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from django.views.generic import DetailView, CreateView, UpdateView, ListView
from musiques.models import Artiste


class ArtisteCreateView(CreateView):
    """
    Définition de la vue pour créer un artiste à partir d'une vue générique
    """
    model = Artiste
    fields = ['nom']


class ArtisteDetailView(DetailView):
    """
    Définition de la vue pour afficher les détails d'un artiste
    """
    model = Artiste


class ArtisteUpdateView(UpdateView):
    model = Artiste
    fields = ['nom']


class ArtisteListView(ListView):

    model = Artiste


def deleteArtiste(request, id):
    Artiste.objects.filter(id=id).delete()
    return redirect(reverse('musiques:artiste-liste'))

musiques/morceau/views.py
from django.shortcuts import render, reverse, redirect
from django.http import HttpResponse
from django.views.generic import DetailView, CreateView, UpdateView, ListView
from musiques.models import Morceau


class MorceauCreateView(CreateView):
    """
    Définition de la vue pour créer un morceau à partir d'une vue générique
    """
    model = Morceau
    fields = ['titre', 'artiste_fk', 'date_sortie']


class MorceauDetailView(DetailView):
    """
    Définition de la vue pour afficher les détails d'un morceau
    """
    model = Morceau


class MorceauUpdateView (UpdateView):
    """
    Définition de la vue pour modifier un morceau à partir d'une vue générique
    """
    model = Morceau
    fields = ['titre', 'artiste_fk', 'date_sortie']


class MorceauListView(ListView):
    model = Morceau


def deleteMorceau(request, id):
    Morceau.objects.filter(id=id).delete()
    return redirect(reverse('musiques:morceau-liste'))

musiques/views.py
# Les vues pour les artistes
from musiques.artistes.views import *

# Les vues pour les morceau
from musiques.morceau.views import *

musiques/templates/musiques/artiste_detail.html
{% extends "musiques/base.html" %}
{% block contenu %}
<section>
    <h1>{{object.nom}}</h1>
    <ul class="list-group">
        {% for morceau in object.morceau_set.all %}
            <li class="list-group-item"><a href="{% url 'musiques:morceau-detail' pk=morceau.pk %}">{{ morceau.titre }}</a></li>
            {% empty %}
            <li class="list-group-item">Pas encore de morceau pour cet artiste.</li>
        {% endfor %}
    </ul>
</section>
{% endblock %}

musiques/templates/musiques/artiste_form.html
{% extends "musiques/base.html" %}
{% block contenu %}
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Save">
    </form>
{% endblock %}

musiques/templates/musiques/artiste_list.html
{% extends "musiques/base.html" %}
{% block contenu %} 
<section class="row" style="padding-top:1em">
        <h1 class="col-sm-4">Artiste</h1>
        <a class="col-sm-2" href="{% url 'musiques:artiste-create'%}">
            <button class="btn btn-success ">Ajouter un Artiste</button>
        </a>
    </section>

<ul class="list-group">
{% for artiste in object_list %}
    <li class="row list-group-item">
        <a class="col-sm-8" href="{% url 'musiques:artiste-detail' pk=artiste.pk %}">{{ artiste.nom }}</a>
        <a href="{% url 'musiques:artiste-update' pk=artiste.pk %}" class="col-sm-2"><button class="btn btn-primary">Modifier</button></a>
        <a href="{% url 'musiques:artiste-delete' id=artiste.pk %}" class="col-sm-2"><button class="btn btn-danger">Supprimer</button></a>
    </li>
{% empty %}
    <li class="list-group-item">Pas encore d'artiste.</li>
{% endfor %}
</ul>
{% endblock %}

musiques/templates/musiques/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mes musiques</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
</head>
<body class="container-fluid">
    

        <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="#">La musique dans la peau</a>
                <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav">
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'musiques:morceau-liste' %}">Liste Musique <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'musiques:artiste-liste' %}">Liste artistes</a>
                    </li>
                  </ul>
                </div>
              </nav>


    {% block contenu %}{% endblock %}    
</body>
</html>

musiques/templates/musiques/morceau_detail.html
{% extends "musiques/base.html" %}
{% block contenu %} 
<section>
    <h1>{{object.titre}}</h1>
    <h2>{{object.date_sortie}}
    <a href="{% url 'musiques:artiste-detail' pk=object.artiste_fk.pk %}"><h2>{{object.artiste_fk}}<h2></a>
    <a href="{% url 'musiques:morceau-delete' id=morceau.pk %}" class="col-sm-2"><button class=" btn btn-danger">Supprimer</button></a>        
</section>
{% endblock %}

musiques/templates/musiques/morceau_form.html
{% extends "musiques/base.html" %}
{% block contenu %} 
<section>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Save">
    </form>
</section>
{% endblock %}

musiques/templates/musiques/morceau_list.html
{% extends "musiques/base.html" %}
{% block contenu %} 
<section class="row" style="padding-top:1em">
    <h1 class="col-sm-4">Morceaux</h1>
    <a class="col-sm-2" href="{% url 'musiques:morceau-create'%}">
        <button class="btn btn-success ">Ajouter un Morceau</button>
    </a>
</section>

<ul class="list-group">
{% for morceau in object_list %}
    <li class="row list-group-item">
        <a class="col-sm-8" href="{% url 'musiques:morceau-detail' pk=morceau.pk %}">{{ morceau.titre }} - {{ morceau.date_sortie }}</a> 
        <a href="{% url 'musiques:morceau-update' pk=morceau.pk %}"  class="col-sm-2"><button class=" btn btn-primary">Modifier</button></a>
        <a href="{% url 'musiques:morceau-delete' id=morceau.pk %}" class="col-sm-2"><button class=" btn btn-danger">Supprimer</button></a>
    </li>
{% empty %}
    <li class="row list-group-item">Pas encore de morceau.</li>
{% endfor %}
</ul>
{% endblock %}